@RELATION smartphone

@ATTRIBUTE Gender {Female, LGBTQ+, Male}
@ATTRIBUTE Age_range {18-25, 26-32, 26-35, 33-40, 36-45, 46-55, 56+, 60+}
@ATTRIBUTE Status {Married, Single, Student, Working, แยกกันอยู่}
@ATTRIBUTE Top3_smartphone_activities {'Art photography, Video editing, Upload stories', 'Chat with family, Read e-books, Listen to radio', 'Cloud apps, Communication / meetings, Social media', 'Communication / meetings, Social media', 'Communication, Take photos, Social media', 'Email, ข่าวสาร, Finance', 'GPS navigation, Check car condition, ฟังพอดแคสต์', 'Online meetings, Schedule management, Email', 'Online shopping, Social media, Finance', 'Online shopping, Track delivery, แชทลูกค้า', 'Play esports, Stream games, แชทชุมชน', 'Play games', 'Play games, Streaming, Social media', 'Play games, Streaming, ถ่ายรูปถ่ายวีดีโอ', 'Play games, Take photos, Watch movies', 'Play games, Take photos/videos', 'Play games, Take photos/videos, Cloud apps', 'Play games, Take photos/videos, Social media', 'Play games, Watch movies, Take photos', 'Product photography, Edit reviews, Online marketplace', 'Read news, Check stocks, Finance', 'Social media, ถ่ายรูปถ่ายวีดีโอ, ดูหนัง/ฟังเพลง', 'Streaming, ถ่ายรูปถ่ายวีดีโอ, Edit video', 'Take photos, Listen to music, Social media', 'Take photos/videos, Communication / meetings, Social media', 'Track delivery, แชทลูกค้า, Email', 'Watch movies / listen to music', 'Watch movies / listen to music, Communication / meetings, Social media', 'Watch movies / listen to music, Play games', 'Watch movies / listen to music, Play games, Cloud apps', 'Watch movies / listen to music, Play games, Communication / meetings', 'Watch movies / listen to music, Play games, Social media', 'Watch movies / listen to music, Play games, Take photos', 'Watch movies / listen to music, Play games, Take photos/videos', 'Watch movies / listen to music, Social media', 'Watch movies / listen to music, Take photos/videos', 'Watch movies / listen to music, Take photos/videos, Communication / meetings', 'Watch movies / listen to music, Take photos/videos, Social media', 'Watch movies, Listen to music, Take photos', 'Watch movies, Play games, Take photos', 'Watch movies, Take photos, Listen to music', 'ติดต่อสื่อสาร/ประชุมงาน, Email, Finance', 'ติ๊กต็อก, Livestream, Search information', 'ถ่ายรูปถ่ายวีดีโอ, ดูหนัง/ฟังเพลง, Online shopping'}
@ATTRIBUTE Frequent_apps {CapCut, Discord, Facebook, 'Facebook Messenger', 'Facebook, Facebook Messenger, Line', 'Facebook, Facebook Messenger, Spotify', 'Facebook, Facebook Messenger, Spotify, TikTok', 'Facebook, TikTok, Line', 'Facebook, YouTube', 'Facebook, YouTube, Facebook Messenger', 'Facebook, YouTube, Facebook Messenger, Spotify', 'Facebook, YouTube, Facebook Messenger, TikTok', Gmail, 'Google Maps', Instagram, 'Instagram, Facebook Messenger, TikTok', 'Instagram, Facebook, Facebook Messenger, Spotify, TikTok', 'Instagram, Facebook, Facebook Messenger, TikTok', 'Instagram, Facebook, Facebook Messenger, TikTok, LINE', 'Instagram, Facebook, Facebook Messenger, TikTok, Telegram', 'Instagram, Facebook, TikTok', 'Instagram, Facebook, YouTube', 'Instagram, Facebook, YouTube, Facebook Messenger', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify, TikTok', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify, TikTok, Telegram', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify, WhatsApp, TikTok, Telegram', 'Instagram, Facebook, YouTube, Facebook Messenger, Telegram', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok, Line', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok, Line, X', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok, Telegram', 'Instagram, Facebook, YouTube, Snapchat, Facebook Messenger, Spotify, TikTok', 'Instagram, Facebook, YouTube, Snapchat, Facebook Messenger, Spotify, WhatsApp, TikTok', 'Instagram, Facebook, YouTube, Snapchat, Facebook Messenger, Spotify, WhatsApp, TikTok, Telegram', 'Instagram, Facebook, YouTube, Spotify, TikTok', 'Instagram, Facebook, YouTube, TikTok', 'Instagram, Spotify, TikTok', 'Instagram, TikTok', 'Instagram, YouTube, Facebook Messenger, Spotify, TikTok', 'Instagram, YouTube, Facebook Messenger, TikTok', 'Instagram, YouTube, Spotify, Telegram', 'Instagram, YouTube, Spotify, TikTok', 'Instagram, YouTube, TikTok', LINE, 'Microsoft Teams', SET, Shopee, Telegram, TikTok, VSCO, WhatsApp, YouTube, 'YouTube, Facebook Messenger, Discord, Wise', 'YouTube, TikTok'}
@ATTRIBUTE Daily_usage_duration {'0-1 hours', '1-3 hours', '3-5 hours', '5-6 hours', '>5 hours'}
@ATTRIBUTE Smartphone_importance {Essential, 'Highly essential', 'Not important', 'Not necessary', 'Somewhat important'}
@ATTRIBUTE Key_factor_online_purchase {Battery, Brand, Camera, Design, Durability, Ecosystem, Features, Performance, Price, 'Product features', 'Product reviews', Reliability, 'Sensor quality', Simplicity, Stability, 'Value for money'}
@ATTRIBUTE Brand_satisfaction NUMERIC
@ATTRIBUTE Purchase_problem {'Cannot physically inspect product', 'Delivery delays/issues', 'High price', 'Payment security concerns', 'Uncertainty about warranty/service', กล้องไม่คมชัด, การคืนสินค้ายุ่งยาก, การจัดส่งล่าช้า, การรับประกันไม่ครอบคลุม, การเปรียบเทียบราคายาก, ความกังวลด้านการรับประกัน, ความกังวลเกี่ยวกับความปลอดภัย, ความกังวลเรื่องความปลอดภัย, ความกังวลเรื่องบริการหลังการขาย, ความซับซ้อนในการชำระเงิน, ความไม่แน่นอนของการรับประกัน, ความไม่แน่นอนเกี่ยวกับบริการหลังการขาย, ความไม่แน่นอนในการรับประกัน, คุณภาพสินค้าไม่ตรงตามที่โฆษณา, ปัญหาการทดลองสินค้า, ปัญหาการบริการหลังการขาย, ปัญหาด้านการชำระเงิน, ปัญหาด้านการทดลองสินค้า, ปัญหาด้านความปลอดภัยของการชำระเงิน, ปัญหาด้านบริการหลังการขาย, ปัญหาบริการหลังการขาย, พื้นที่เก็บข้อมูลไม่พอ, ระบบค้างบ่อย, ระบบล้าสมัย, หน้าจอมีจุดตาย, เครื่องร้อนบ่อย, ไม่มี, ไม่มีปัญหา, ไม่สามารถทดลองสินค้าได้, ไม่สามารถสัมผัสสินค้าก่อนซื้อได้, ไม่สามารถสัมผัสสินค้าได้จริง, ไม่แน่นอนเกี่ยวกับการรับประกัน}
@ATTRIBUTE Monthly_income {'100,001-150,000 THB', '15,001-20,000 THB', '20,001-30,000 THB', '25,001-35,000 THB', '30,001-40,000 THB', '30,001-50,000 THB', '50,001-100,000 THB', '<15,000 THB', 'มากกว่า 50,001 บาทขึ้นไป'}
@ATTRIBUTE Occupation {Artist, 'Business owner', 'Civil servant', 'Content creator', 'Delivery staff', Employee, 'Factory worker', Freelancer, Housewife, Investor, 'Logistics staff', Manager, 'Office worker', 'Online seller', 'Private company employee', Retired, Student}
@ATTRIBUTE Current_brand {Apple, Calculator, Huawei, Infinix, Oppo, Other, Realme, 'Realme 7 5G', Redmi, Samsung, Vivo, Xiaomi}

