@RELATION smartphone

@ATTRIBUTE Gender {Female, LGBTQ+, Male}
@ATTRIBUTE Age_range {18-25, 26-32, 26-35, 33-40, 36-45, 46-55, 56+, 60+}
@ATTRIBUTE Status {Married, Single, Student, Working}
@ATTRIBUTE Top3_smartphone_activities {'/, Email, Finance', 'Art photography, Video editing, Upload stories', 'Chat with family, Read e-books, Listen to radio', 'Cloud apps, Communication/meetings, Social media', 'Communication, Take photos, Social media', 'Communication/meetings, Social media', 'Email, , Finance', 'GPS navigation, Check car condition, Listen to podcasts', 'Online meetings, Schedule management, Email', 'Online shopping, Social media, Finance', 'Online shopping, Track delivery, Customer chat', 'Play esports, Stream games, Community chat', 'Play games', 'Play games, Streaming, Social media', 'Play games, Streaming, Take photos/videos', 'Play games, Take photos, Watch movies', 'Play games, Take photos/videos', 'Play games, Take photos/videos, Cloud apps', 'Play games, Take photos/videos, Social media', 'Play games, Watch movies, Take photos', 'Product photography, Edit reviews, Online marketplace', 'Read news, Check stocks, Finance', 'Social media, Take photos/videos, Watch movies/Listen to music', 'Streaming, Take photos/videos, Edit video', 'Take photos, Listen to music, Social media', 'Take photos/videos, Communication/meetings, Social media', 'Take photos/videos, Watch movies/Listen to music, Online shopping', 'TikTok, Livestream, Search information', 'Track delivery, Customer chat, Email', 'Watch movies, Listen to music, Take photos', 'Watch movies, Play games, Take photos', 'Watch movies, Take photos, Listen to music', 'Watch movies/listen to music', 'Watch movies/listen to music, Communication/meetings, Social media', 'Watch movies/listen to music, Play games', 'Watch movies/listen to music, Play games, Cloud apps', 'Watch movies/listen to music, Play games, Communication/meetings', 'Watch movies/listen to music, Play games, Social media', 'Watch movies/listen to music, Play games, Take photos', 'Watch movies/listen to music, Play games, Take photos/videos', 'Watch movies/listen to music, Social media', 'Watch movies/listen to music, Take photos/videos', 'Watch movies/listen to music, Take photos/videos, Communication/meetings', 'Watch movies/listen to music, Take photos/videos, Social media'}
@ATTRIBUTE Frequent_apps {CapCut, Discord, Facebook, 'Facebook Messenger', 'Facebook, Facebook Messenger, Line', 'Facebook, Facebook Messenger, Spotify', 'Facebook, Facebook Messenger, Spotify, TikTok', 'Facebook, TikTok, Line', 'Facebook, YouTube', 'Facebook, YouTube, Facebook Messenger', 'Facebook, YouTube, Facebook Messenger, Spotify', 'Facebook, YouTube, Facebook Messenger, TikTok', Gmail, 'Google Maps', Instagram, 'Instagram, Facebook Messenger, TikTok', 'Instagram, Facebook, Facebook Messenger, Spotify, TikTok', 'Instagram, Facebook, Facebook Messenger, TikTok', 'Instagram, Facebook, Facebook Messenger, TikTok, LINE', 'Instagram, Facebook, Facebook Messenger, TikTok, Telegram', 'Instagram, Facebook, TikTok', 'Instagram, Facebook, YouTube', 'Instagram, Facebook, YouTube, Facebook Messenger', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify, TikTok', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify, TikTok, Telegram', 'Instagram, Facebook, YouTube, Facebook Messenger, Spotify, WhatsApp, TikTok, Telegram', 'Instagram, Facebook, YouTube, Facebook Messenger, Telegram', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok, Line', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok, Line, X', 'Instagram, Facebook, YouTube, Facebook Messenger, TikTok, Telegram', 'Instagram, Facebook, YouTube, Snapchat, Facebook Messenger, Spotify, TikTok', 'Instagram, Facebook, YouTube, Snapchat, Facebook Messenger, Spotify, WhatsApp, TikTok', 'Instagram, Facebook, YouTube, Snapchat, Facebook Messenger, Spotify, WhatsApp, TikTok, Telegram', 'Instagram, Facebook, YouTube, Spotify, TikTok', 'Instagram, Facebook, YouTube, TikTok', 'Instagram, Spotify, TikTok', 'Instagram, TikTok', 'Instagram, YouTube, Facebook Messenger, Spotify, TikTok', 'Instagram, YouTube, Facebook Messenger, TikTok', 'Instagram, YouTube, Spotify, Telegram', 'Instagram, YouTube, Spotify, TikTok', 'Instagram, YouTube, TikTok', LINE, 'Microsoft Teams', SET, Shopee, Telegram, TikTok, VSCO, WhatsApp, YouTube, 'YouTube, Facebook Messenger, Discord, Wise', 'YouTube, TikTok'}
@ATTRIBUTE Daily_usage_duration {'0-1 hours', '1-3 hours', '3-5 hours', '5-6 hours', '>5 hours'}
@ATTRIBUTE Smartphone_importance {Essential, 'Highly essential', 'Not important', 'Not necessary', 'Somewhat important'}
@ATTRIBUTE Key_factor_online_purchase {Battery, Brand, Camera, Design, Durability, Ecosystem, Features, Performance, Price, 'Product features', 'Product reviews', Reliability, 'Sensor quality', Simplicity, Stability, 'Value for money'}
@ATTRIBUTE Brand_satisfaction NUMERIC
@ATTRIBUTE Purchase_problem {'After-sales service issues', 'Blurry camera', 'Cannot try product before buying', 'Complex payment process', 'Concerns about after-sales service', 'Concerns about payment security', 'Concerns about safety', 'Concerns about warranty', 'Dead pixels on screen', 'Delivery delays', 'Device overheats', 'Difficult return process', 'Difficult to compare prices', 'Insufficient storage', 'Issues with delivery', 'Limited warranty coverage', 'No problems', 'Outdated system', 'Payment issues', 'Payment security concerns', 'Product is too expensive', 'Product quality doesn't match ads', 'System crashes frequently', 'Unable to inspect product', 'Uncertainty about after-sales service', 'Uncertainty about warranty', 'Warranty or service concerns'}
@ATTRIBUTE Monthly_income {' 50001 ', 100001-150000, 15001-20000, 20001-30000, 25001-35000, 30001-40000, 30001-50000, 50001-100000, 'Less than 15000'}
@ATTRIBUTE Occupation {Artist, 'Business owner', 'Civil servant', 'Content creator', 'Delivery staff', Employee, 'Factory worker', Freelancer, Housewife, Investor, 'Logistics staff', Manager, 'Office worker', 'Online seller', 'Private company employee', Retired, Student}
@ATTRIBUTE Current_brand {Apple, Calculator, Huawei, Infinix, Oppo, Other, Realme, 'Realme 7 5G', Redmi, Samsung, Vivo, Xiaomi}