services:
  - type: web
    name: waka-api
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1