services:
  - type: web
    name: waka-api
    env: node
    buildCommand: apt-get update && apt-get install -y openjdk-17-jre-headless && yarn install && yarn build && mkdir -p dist/uploads && mkdir -p dist/model
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1