services:
  - type: web
    name: waka-api
    env: node
    buildCommand: mkdir -p java && curl -L -o java/jre17.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10+7/OpenJDK17U-jre_x64_linux_hotspot_17.0.10_7.tar.gz && tar -xzf java/jre17.tar.gz -C java --strip-components=1 && export PATH=$PWD/java/bin:$PATH && yarn install && yarn build && mkdir -p dist/uploads && mkdir -p dist/model
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 1